name: CI-CD K8S Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:

# ---------------- TEST ----------------

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - run: npm install

      - run: npm test


# ---------------- LINT ----------------

  lint:

    runs-on: ubuntu-latest

    needs: test

    steps:

      - uses: actions/checkout@v4

      - run: npm install

      - run: npm run lint



# ---------------- BUILD ----------------

  build:

    runs-on: ubuntu-latest

    needs: lint

    steps:

      - uses: actions/checkout@v4

      - run: npm install

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build image
        run: |
          pwd
          ls -la
          docker build -f Dockerfile -t anju557/github-actions-project .



# ---------------- SCAN ----------------

  scan:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: anju557/github-actions-project



# ---------------- PUSH ----------------

  push:

    runs-on: ubuntu-latest

    needs: scan

    steps:

      - uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build image
        run: docker build -f Dockerfile -t anju557/github-actions-project .

      - name: Push image
        run: docker push anju557/github-actions-project



# ---------------- DEPLOY ----------------

  deploy:

    runs-on: ubuntu-latest

    needs: push

    steps:

      - name: Deploy to K8S
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}

          script: |
            cd ~/github-actions-project/k8s
            docker pull anju557/github-actions-project
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
            kubectl rollout restart deployment github-actions-project
            kubectl get pods
